models:
  gemini-2.5-flash-batch:
    type: "api"
    mode: "batch"
    model_name: "gemini-2.5-flash-001"
    api_key: "${GEMINI_API_KEY}"
    project_id: "your-gcp-project-id" # <-- IMPORTANT: CHANGE THIS
    location: "us-central1"

    batch_config:
      gcs_bucket: "gs://your-benchmark-suite-bucket" # <-- IMPORTANT: CHANGE THIS
      upload_images: true 
      gcs_image_prefix: "gs://your-benchmark-suite-bucket/erqa/images"
      output_prefix: "gs://your-benchmark-suite-bucket/erqa/batch_outputs"
      wait_for_completion: true
      poll_interval: 60

tasks:
  erqa:
    type: "erqa"
    data_path: "data/erqa" 
    metrics: ["accuracy"]

logging:
  output_dir: "results"