models:
  gemini-2.0-flash-lite-batch:
    type: "api"
    mode: "batch"
    model_name: "gemini-2.0-flash-lite-001"
    project_id: "your-project-id" # <-- IMPORTANT: CHANGE THIS
    location: "us-central1"
    max_tokens: 8192
    temperature: 1.0
    top_k: 64
    top_p: 0.95

    batch_config:
      gcs_bucket: "gs://your-bucket-name" # <-- IMPORTANT: CHANGE THIS
      upload_images: false 
      gcs_image_prefix: "gs://your-bucket-name/erqa/images" # <--- Not required if already uploaded
      output_prefix: "gs://your-bucket-name/batch_output/erqa/gemini_2_0_flash_lite"
      wait_for_completion: true
      poll_interval: 60

tasks:
  erqa:
    type: "erqa"
    data_path: "data/erqa" 
    metrics: ["accuracy"]

logging:
  output_dir: "results"