models:
  gemma:
    type: "ollama"
    model_name: "gemma3:27b"
    max_tokens: 128000
    temperature: 1.0
    top_k: 64
    top_p: 0.95

tasks:
  erqa:
    type: "erqa"
    data_path: "data/erqa"
    sample_size: 400
    random_seed: 42
    metrics: ["accuracy"]

logging:
  wandb:
    project: "multimodal-benchmarks"
    entity: "${WANDB_ENTITY}"
    enabled: True
    run_name: "erqa-evaluation"
  save_predictions: True
  output_dir: "results"
